apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: my-php-app:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

